### PR TITLE
Update for the SR2019 game

### PR DESCRIPTION
**Pull request by PeterJCLaw**
Fixes https://github.com/srobo/tasks/issues/48

### CODE REVIEW

**Review by RealOrangeOne — APPROVED** [review]
Code looks ok, and seems to do what it's meant to. Whether it works is a different story

**Comment by PeterJCLaw** [comment]
I keep thinking that I don't have an Odroid to test this on, however I have two whole kits here. I'll try to test this this evening.

**Comment by PeterJCLaw** [comment]
Scratch that, testing this will need to wait until tomorrow evening. We can ship other things without this though.

**Comment by PeterJCLaw** [comment]
(I wrote this last night, but appear not to have posted it)

Testing this is proving challenging. While I can make _other_ changes to the `sr.robot` egg within the squashfs, when I try to deploy this change the Odroid doesn't boot fully. No `log.txt`, no flashing start button.

It's not clear what's causing this as I have no idea where to look for any error messages. I've tried a couple of different ways of editing the .egg zip archive to change the `vision.py`, and neither works. (One is the same method I successfully used to add a `print` statement elsewhere; I've not tested the other method with other changes).

Ideas to try at some point:
- copy the `vision.py` onto the usb stick and see if we can import it directly from user code while using a known-working squashfs
- make a different (and smaller, simper) change to the `vision.py` in the archive

**Comment by PeterJCLaw** [comment]
So the fix here turns out to be incredibly simple. I'd forgotten to update the package level constant re-exports in the `__init__.py`.

**Pull request merged**
